name: Add Test To Repository (.repo-add-test)


on:
  issue_comment:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Store required context in environment
        run: |
          echo ::set-env name=COMMENT_BODY::$(
            jq -rc '.comment.body' $GITHUB_EVENT_PATH
          )
          echo ::set-env name=ISSUE_NUMBER::$(
            jq -rc .issue.number $GITHUB_EVENT_PATH
          )
          echo ::set-env name=ISSUE_HTML_URL::$(
            jq -rc '.issue.html_url' $GITHUB_EVENT_PATH
          )
          echo ::set-env name=ACTION_HTML_URL::$(
            echo https://github.com/${GITHUB_REPOSITORY}/actions
          )
          echo ::set-env name=ISSUE_ACTOR::$(printf ${GITHUB_ACTOR})

      - name: Match the `repo-add-test` chatop or bail
        run: echo ${COMMENT_BODY} | egrep -q "^\.repo-add-test "

      - name: Debug Context
        run: |
          jq -rc '.' $GITHUB_EVENT_PATH

      - name: Acknowledge chatop on calling Issue
        uses: octokit/request-action@v1.1.0
        id: ack_comment
        with:
          route: POST /repos/:owner/:repo/issues/${{ env.ISSUE_NUMBER }}/comments
          body: |
            👋 @${{ env.ISSUE_ACTOR }} - Starting Action.
            Follow along on the [Actions tab](${{ env.ACTION_HTML_URL }}).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse `.repo-add-test` arguments
        run: |
          echo ::set-env name=TEST_NAME::$(echo ${COMMENT_BODY} | cut -d ' ' -f 2)

      - name: Checkout the repo to make edits
        uses: actions/checkout@master

      - name: Add test to `test/` and `example/`
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/examples/${TEST_NAME}
          touch ${GITHUB_WORKSPACE}/examples/${TEST_NAME}/{main,outputs}.tf

          TEST_NAME_UNDERSCORES=$(echo $TEST_NAME | tr '-' '_')
          mkdir -p ${GITHUB_WORKSPACE}/test/${TEST_NAME}
          touch ${GITHUB_WORKSPACE}/test/${TEST_NAME}/${TEST_NAME_UNDERSCORES}_test.go

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Auto-generated test case
          author-email: hubot@github.com
          author-name: Hubot
          title: Add Test Case To Terraform Module Repository
          body: |
            This PR was generated by an Action. See `.github/workflows` for details.
            /cc ${{ env.ISSUE_HTML_URL }}
            /cc @${{ env.ISSUE_ACTOR }}
          branch: repo-add-test
